Initial mqtt port
spring-cloud-stream-app-starters/mqtt pull request #1
Opened 2017-04-28 09:12 UTC by jvalkeal

- Porting mqtt module as source and sink apps.
- Fixes spring-cloud-stream-app-starters/app-starters-release#8
- Fixes spring-cloud-stream-app-starters/app-starters-release#13

2017-04-28 17:33 UTC, garyrussell requested changes

2017-04-28 17:33 UTC, garyrussell commented on README.adoc
> +include::spring-cloud-starter-stream-sink-mqtt/README.adoc[]
`s/Rabbit/MQTT/` (both titles)

2017-04-28 17:33 UTC, garyrussell commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	private String url = "tcp://localhost:1883";
This should be `String[]` - Spring will parse the CDL - the factory setter takes `String[]` (varargs).

2017-04-28 17:33 UTC, garyrussell commented on mqtt-app-starters-test-support/src/main/java/org/springframework/cloud/stream/app/test/mqtt/MqttRule.java
> +		} catch (Exception e) {
catch on new line.

2017-04-28 17:33 UTC, garyrussell commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttConfiguration.java
> +		} else if (ObjectUtils.nullSafeEquals(mqttProperties.getPersistence(), "memory")) {
else on new line

2017-04-28 17:33 UTC, garyrussell commented on mqtt-app-starters-test-support/src/main/java/org/springframework/cloud/stream/app/test/mqtt/MqttRule.java
> +public class MqttRule extends TestWatcher implements TestRule {
For consistency with other starters, this should really extend `AbstractExternalResourceTestSupport`.

2017-04-28 18:04 UTC, sobychacko commented
We might want to set the version of this project at 1.0.0.BUILD-SNAPSHOT as this is a new addition to app starters.

2017-04-29 07:40 UTC, jvalkeal commented
@sobychacko This versioning is one of a weirdest things in apps. While it's true that `1.0.0` is probably more appropriate but as all apps currently have same version we haven't followed this approach that new app starts from `1.0.0`. Or is it a case that since initial `1.0.0` release we haven't added a singe new app?

2017-05-01 15:44 UTC, sobychacko commented
@jvalkeal we had new apps in bacon, but because of some special circumstances, we needed to baseline everything to 1.2.0. But i think going forward, for new app starters, we should start from 1.0.0.

2017-05-01 17:48 UTC, artembilan requested changes
That's all from my side.
Nothing critical at a glance.
Just some concerns which require a bit more clarification.

2017-05-01 17:48 UTC, artembilan commented on README.adoc
> +To learn more about this application and the supported properties, please review the following link.
> Source and Sink

So, might be better to tell like: " these applications "

2017-05-01 17:48 UTC, artembilan commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttConfiguration.java
> +public class MqttConfiguration {
Why this isn't marked with the `@Configuration`?
Does it really work as is?

2017-05-01 17:48 UTC, artembilan commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	private String[] url = new String[] { "tcp://localhost:1883" };
Some of the properties might be required - need particular validations to protect against misconfiguration

2017-05-01 17:48 UTC, artembilan commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkConfiguration.java
> +		messageHandler.setAsync(true);
`this.properties.isAsync()` must be used.

2017-05-01 17:48 UTC, artembilan commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +@ConfigurationProperties("mqtt")
I wonder how does that work if we use the same prefix on different `@ConfigurationProperties` in the same app...
I mean that `@EnableConfigurationProperties({ MqttProperties.class, MqttSinkProperties.class })` and this `mqtt` prefix on the `MqttProperties` as well. 

Does it mean that Boot properly merge them into one set and then is able to distribute provided properties to proper classes?
Just confused a bit and would like to have some clarification.
Thanks

2017-05-01 17:48 UTC, artembilan commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +	private String clientId = "scdf.mqtt.client.id.sink";
I still don't understand why do we mention SCDF in these apps?
That's good to demonstrate that our products works together and it is really in our interests to promote our products, but these SCSt apps are supposed to be working as a stand-along micorservices or as a part of some other platform.

2017-05-01 17:48 UTC, artembilan commented on spring-cloud-starter-stream-source-mqtt/pom.xml
> +			<artifactId>spring-integration-java-dsl</artifactId>
This dependency is out of use.

2017-05-01 19:41 UTC, jvalkeal commented on spring-cloud-starter-stream-source-mqtt/pom.xml
> +			<artifactId>spring-integration-java-dsl</artifactId>
Yeah, that was brought over from rabbit app, wonder why it's there?

2017-05-01 19:42 UTC, jvalkeal commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +	private String clientId = "scdf.mqtt.client.id.sink";
When porting from xd, it uses xd in id so followed a pattern. Wonder what it should be?

2017-05-01 19:43 UTC, jvalkeal commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +@ConfigurationProperties("mqtt")
Doesn't matter as boot will simply bind to both classes. We don't have shared `MqttProperties` anywhere and didn't want to duplicate same properties.

2017-05-01 19:43 UTC, jvalkeal commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkConfiguration.java
> +		messageHandler.setAsync(true);
Good catch, I'll need to add that.

2017-05-01 19:45 UTC, jvalkeal commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttConfiguration.java
> +public class MqttConfiguration {
If it's imported `@Configuration' is not needed.

2017-05-01 19:46 UTC, artembilan commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +@ConfigurationProperties("mqtt")
But you did. `Sink` and `Source` variants have many same properties...

2017-05-01 19:50 UTC, jvalkeal commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	private String[] url = new String[] { "tcp://localhost:1883" };
We used validators in xd to fail fast but it looks like we dropped using those. Not sure what to do?

2017-05-01 19:55 UTC, artembilan commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	private String[] url = new String[] { "tcp://localhost:1883" };
Not sure what you mean about "dropped", but even mentioned `RabbitSourceProperties` has validation annotations

2017-05-01 20:07 UTC, artembilan commented on spring-cloud-starter-stream-source-mqtt/pom.xml
> +			<artifactId>spring-integration-java-dsl</artifactId>
Yep! We don't need it there as well. Good catch!

2017-05-02 07:48 UTC, jvalkeal commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttConfiguration.java
> +public class MqttConfiguration {
I can add it, makes it less confusing.

2017-05-02 08:02 UTC, jvalkeal commented on spring-cloud-starter-stream-sink-mqtt/src/main/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkProperties.java
> +@ConfigurationProperties("mqtt")
Point was to separate connection properties as what are used in a shared config creating `mqttClientFactory`

2017-05-02 14:14 UTC, artembilan requested changes
I don't have anything to nit-pick any more.

2017-05-02 14:14 UTC, artembilan commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	@Size(min = 1)
Adding validation annotations requires in the latest Boot to add `@Validated` to the class level: https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/82

2017-05-02 14:14 UTC, artembilan commented on spring-cloud-starter-stream-sink-mqtt/src/test/java/org/springframework/cloud/stream/app/mqtt/sink/MqttSinkTests.java
> +//import org.springframework.cloud.stream.binder.test.junit.rabbit.RabbitTestSupport;
Redundant code

2017-05-02 14:26 UTC, jvalkeal commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	@Size(min = 1)
I can add it but weird as I got validation errors without it.

2017-05-02 14:28 UTC, artembilan commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	@Size(min = 1)
@jvalkeal , I pointed you a GH issue originated this request.
Not my call to do that. That is a warn from Boot.

2017-05-02 14:38 UTC, jvalkeal commented on mqtt-app-starters-common/src/main/java/org/springframework/cloud/stream/app/mqtt/MqttProperties.java
> +	@Size(min = 1)
ah, warning. ok I'll add it.

2017-05-05 20:38 UTC, artembilan approved these changes
I don't have objections on this PR any more.
Can be merged.

Tested via RabbitMQ MQTT plugin. 
I published message to the subscription queue and get answer in the artificially bound `foo` queue like:
```
Exchange 	output
Routing Key 	output
Redelivered 	○
Properties 	
priority:	0
delivery_mode:	2
headers:	
mqtt_retained:	false
mqtt_qos:	0
mqtt_topic:	mqtt-subscription-stream/client/id/sourceqos0
mqtt_duplicate:	false
contentType:	text/plain
content_type:	text/plain
Payload
60 bytes
Encoding: string
	

rty fghjkmhgjkm hgjk hgjkh gjkhgjk ghjk ghjk ghkj ghjk hgj k
```

Tested `sink` there as well via `amqp.topic` and `foo` queue bound via `stream.mqtt` routing key:
```
Exchange 	amq.topic
Routing Key 	stream.mqtt
Redelivered 	○
Properties 	
delivery_mode:	2
headers:	
x-mqtt-publish-qos:	1
x-mqtt-dup:	false
Payload
13 bytes
Encoding: string
	

fghfghfghfgdh
```

2017-05-05 20:38 UTC, artembilan commented on mqtt-app-dependencies/pom.xml
> +	<version>1.2.1.BUILD-SNAPSHOT</version>
There is a discussion on the Tensorflow PR that new app starter should have version as `1.0.0`.

@sobychacko , confirm, please

2017-05-05 20:50 UTC, jvalkeal commented on mqtt-app-dependencies/pom.xml
> +	<version>1.2.1.BUILD-SNAPSHOT</version>
I still strongly disagree going with with any other version other than 1.2.x as all others are 1.2.x as well. I would just be confusing.

2017-05-16 17:14 UTC, garyrussell approved these changes

2017-05-16 17:14 UTC, garyrussell commented
Merged as fbc87b2bf542265eb657a59386dcd0738d57e2bf with version 1.0.0, some minor checkstyle changes and switch to use AssertJ.

2017-05-16 17:14 UTC, closed without merging